# Generated by Django 5.2.7 on 2025-12-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product_price')),
                ('all', models.IntegerField(verbose_name='all')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='promotion_name')),
                ('description', models.TextField(verbose_name='promotion_description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='promotion_price')),
                ('condition', models.IntegerField(verbose_name='promotion_condition')),
                ('active', models.BooleanField(verbose_name='is_active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.IntegerField(verbose_name='buy')),
                ('user_name', models.CharField(verbose_name='user_name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
