# Generated by Django 5.2.7 on 2025-12-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='price',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
